### ISSUE TITLE
Some improvements and Asus Z97 Deluxe fixes

### ISSUE THREAD

**Issue by eos1d3** [POP3UR/EFI-Opencore-z97n-Big-Sur#1]
Thanks for the EFI and my Asus Z97 Deluxe is working with Big Sur 11.1 now. (BIOS must be downgraded to 1304 because of Asus faulty BIOS with NVRAM issue)

There are some improvements for this config:

1. PlayChime is changed to String from Boolean since OC 0.6.4, 
```
Auto — Enables chime when StartupMute NVRAM variable is not present or set to 00.
Enabled — Enables chime unconditionally.
Disabled — Disables chime unconditionally.

```
see: https://dortania.github.io/docs/latest/Configuration.html

For example, it can be defined as:
```
<key>PlayChime</key>
<string>Enabled</string>
```

And the value of SystemAudioVolume is wrong, it should be:
```
<key>SystemAudioVolume</key>
<data>0x46</data>
```

2. One of main problems is FakeSMC and VirtualSMC are used at the same time. It creates reboot and shutdown issues. By removing FakeSMC in `config.plist` and EFI fixes the problems.

3. These drivers and kexts are not required. They can be removed in `config.plist` and EFI folder too.
```
EnableLidWake.kext
FakeSMC.kext
NightShiftEnabler.kext
NoTouchID.kext
VBoxHfs.efi (replaced with HpfPlus.efi)
```

**Comment by Asgardsurfer** [comment]
Hello POP3UR, just wanted to thank you for sharing your EFI folder, made my transition so much easier!
I  would have sent you an e-mail instead but did not find one.
Merci!!!
